# golangci-lint v2 configuration for boilerplate project
# Based on Go best practices and Uber Style Guide

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  # v2 uses 'default' instead of enable-all/disable-all
  default: standard # Options: all, standard, none, fast

  enable:
    # Essential linters (Uber recommended minimum)
    - errcheck # Check for unchecked errors
    - goimports # Format imports
    - govet # Official Go static analyzer
    - staticcheck # Advanced static analysis

    # Additional security & quality linters
    - gosec # Security issues
    - gosimple # Simplification suggestions
    - ineffassign # Detect ineffectual assignments
    - unused # Detect unused code
    - misspell # Detect misspelled words
    - unconvert # Remove unnecessary conversions
    - unparam # Detect unused function parameters
    - gocritic # Comprehensive checks
    - bodyclose # Check HTTP response body closed
    - noctx # Detect HTTP requests without context

    # Dependency and modernization linters
    - usestdlibvars # Suggest using stdlib constants

  disable:
    - exhaustive # Too strict
    - exhaustruct # Too strict
    - gochecknoglobals
    - gochecknoinits
    - cyclop # Complex cyclomatic complexity
    - funlen # Function length limit
    - lll # Line length limit
    - wsl # Whitespace linter (too opinionated)
    - depguard # Temporarily disabled due to configuration issues
    - revive # Temporarily disabled (documentation not required)

  # v2: Linter settings now under linters section
  settings:
    goimports:
      local-prefixes: github.com/marcelofabianov/boilerplate

    # Depguard: Control which packages can be imported
    # Block only deprecated or problematic packages
    depguard:
      rules:
        prevent-deprecated:
          files:
            - $all
          deny:
            # Deprecated packages
            - pkg: "io/ioutil"
              desc: "Use os and io packages instead (ioutil is deprecated since Go 1.16)"
            - pkg: "github.com/pkg/errors"
              desc: "Use standard errors package or custom implementation"
            - pkg: "golang.org/x/net/context"
              desc: "Use context from standard library"

    # Revive: Enhanced configuration
    revive:
      # Increased confidence for fewer false positives
      confidence: 0.8
      severity: warning
      enable-all-rules: false
      rules:
        # Error handling
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: errorf

        # Context handling
        - name: context-as-argument
          arguments:
            - allowTypesBefore: "*testing.T"
        - name: context-keys-type

        # Code quality
        - name: blank-imports
        - name: dot-imports
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
        - name: unused-parameter
        - name: unused-receiver
        - name: useless-break

        # Naming conventions
        - name: var-naming
          arguments:
            - [
                "ID",
                "URL",
                "HTTP",
                "JSON",
                "API",
                "UUID",
                "SQL",
                "DB",
                "UID",
                "GID",
              ]
        - name: receiver-naming
        - name: time-naming
        - name: var-declaration
        - name: package-comments
          arguments:
            - ^.* # Allow any comment

        # Code style
        - name: indent-error-flow
        - name: if-return
        - name: increment-decrement
        - name: range
        - name: range-val-in-closure
        - name: range-val-address

        # Exported entities
        - name: exported
          arguments:
            - "checkPrivateReceivers"
            - "sayRepetitiveInsteadOfStutters"

        # Return values
        - name: unexported-return
        - name: confusing-results
        - name: identical-branches

        # Functions
        - name: redefines-builtin-id
        - name: function-length
          arguments: [50, 0] # Max 50 statements
        - name: cognitive-complexity
          arguments: [15] # Max cognitive complexity
        - name: cyclomatic
          arguments: [15] # Max cyclomatic complexity
        - name: max-public-structs
          arguments: [5] # Max 5 public structs per file

        # Comments and documentation
        - name: comment-spacings
        - name: comments-density
          arguments: [25] # At least 25% comment density

        # Optimization
        - name: string-of-int
        - name: early-return
        - name: optimize-operands-order
        - name: use-any

        # Best practices
        - name: bool-literal-in-expr
        - name: constant-logical-expr
        - name: defer
          arguments:
            - ["call-chain", "loop", "method-call", "recover", "return"]
        - name: duplicated-imports
        - name: import-shadowing
        - name: modifies-parameter
        - name: modifies-value-receiver
        - name: struct-tag
        - name: time-equal
        - name: unconditional-recursion
        - name: waitgroup-by-value
        - name: atomic
        - name: deep-exit
        - name: flag-parameter
        - name: unnecessary-stmt

    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (io.Closer).Close
        - (*database/sql.Rows).Close

    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G104 # Audit errors not checked (covered by errcheck)

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
      disabled-checks:
        - commentFormatting
        - whyNoLint

    staticcheck:
      checks: ["all"]

    govet:
      enable-all: true
      disable:
        - shadow # Too many false positives
        - fieldalignment # Too strict for development

# v2: Integrated formatter support
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports

issues:
  # v2: Explicit exclusion presets (no defaults)
  exclude-use-default: false

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic

    # Exclude cyclomatic complexity for main packages
    - path: cmd/
      linters:
        - gocyclo

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
